version: "3.9"
services:
    mysql_db: 
        image: mysql:latest
        container_name: mysql__
        hostname: 127.0.0.1:127.0.0.1
        ports: 
            - 3306:3306
        volumes:
            - ./mysqlData:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 12345678
        restart: always
    spring:
        build: .
        # name: spring
        hostname: 127.0.0.1:127.0.0.1
        ports: 
            - 8000:8000
        volumes:
            - ./springData:/files_for_db
        restart: always
        links: 
            - mysql_db