[package]
name = "Big_letters"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rui = "0.6.0"
sys-locale = "0.3.0"

[profile.release]
opt-level = 3
